-- Add applicant identity and address fields

ALTER TABLE quotes
  ADD COLUMN IF NOT EXISTS first_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address text NOT NULL DEFAULT '';

ALTER TABLE quotes
  ALTER COLUMN first_name DROP DEFAULT,
  ALTER COLUMN last_name DROP DEFAULT,
  ALTER COLUMN email DROP DEFAULT,
  ALTER COLUMN address DROP DEFAULT;
